-- MySQL Script generated by MySQL Workbench
-- sex 17 abr 2026 12:46:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema_decisoes
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sistema_decisoes` ;

-- -----------------------------------------------------
-- Schema sistema_decisoes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_decisoes` ;
USE `sistema_decisoes` ;

-- -----------------------------------------------------
-- Table `sistema_decisoes`.`votacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_decisoes`.`votacoes` ;

CREATE TABLE IF NOT EXISTS `sistema_decisoes`.`votacoes` (
  `idVotacoes` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `dataCriacao` DATETIME NOT NULL,
  `prazo_final` DATETIME NOT NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 'ABERTA',
  PRIMARY KEY (`idVotacoes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_decisoes`.`opcoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_decisoes`.`opcoes` ;

CREATE TABLE IF NOT EXISTS `sistema_decisoes`.`opcoes` (
  `idOpcoes` INT NOT NULL AUTO_INCREMENT,
  `textoOpcao` VARCHAR(45) NOT NULL,
  `votacoes_idVotacoes` INT NOT NULL,
  PRIMARY KEY (`idOpcoes`),
  INDEX `fk_opcoes_votacoes1_idx` (`votacoes_idVotacoes` ASC) VISIBLE,
  CONSTRAINT `fk_opcoes_votacoes1`
    FOREIGN KEY (`votacoes_idVotacoes`)
    REFERENCES `sistema_decisoes`.`votacoes` (`idVotacoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_decisoes`.`votos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_decisoes`.`votos` ;

CREATE TABLE IF NOT EXISTS `sistema_decisoes`.`votos` (
  `idVotos` INT NOT NULL,
  `matriculaUsuario` VARCHAR(45) NOT NULL,
  `votacoes_idVotacoes` INT NOT NULL,
  `opcoes_idOpcoes` INT NOT NULL,
  PRIMARY KEY (`idVotos`),
  INDEX `fk_votos_votacoes1_idx` (`votacoes_idVotacoes` ASC) VISIBLE,
  INDEX `fk_votos_opcoes1_idx` (`opcoes_idOpcoes` ASC) VISIBLE,
  UNIQUE INDEX `id_voto_unico` (`matriculaUsuario` ASC, `votacoes_idVotacoes` ASC) VISIBLE,
  CONSTRAINT `fk_votos_votacoes1`
    FOREIGN KEY (`votacoes_idVotacoes`)
    REFERENCES `sistema_decisoes`.`votacoes` (`idVotacoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_votos_opcoes1`
    FOREIGN KEY (`opcoes_idOpcoes`)
    REFERENCES `sistema_decisoes`.`opcoes` (`idOpcoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

USE sistema_decisoes;
ALTER TABLE votacoes MODIFY idVotacoes INT AUTO_INCREMENT;
ALTER TABLE opcoes MODIFY idOpcoes INT AUTO_INCREMENT;
ALTER TABLE votos MODIFY idVotos INT AUTO_INCREMENT;
